// <auto-generated />
using DotNET_Console_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20250328013711_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasDatabaseName("FK_Model_Manufacturer");

                    b.ToTable("model");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("CHAR(17)")
                        .HasColumnName("vin");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<int?>("ModelID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_year");

                    b.HasKey("VIN");

                    b.HasIndex("ModelID")
                        .HasDatabaseName("FK_Vehicle_Model");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Vehicle_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
