// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DotNET_Console_Application.Models;
#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20250319014608_ForeignKeySeedData")]
    partial class ForeignKeySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DotNET_Console_Application.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<int?>("InstructorID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("InstructorID")
                        .HasDatabaseName("FK_Course_Instructor");

                    b.ToTable("course");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Code = "COMP101",
                            InstructorID = -1,
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            ID = -2,
                            Code = "DATA101",
                            InstructorID = -1,
                            Name = "Introduction to Databases"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.ToTable("instructor");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            FirstName = "John",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CourseID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.HasIndex("CourseID")
                        .HasDatabaseName("FK_Student_Course");

                    b.ToTable("student");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Course", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Course_Instructor");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Student_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
