// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.Models;

#nullable disable

namespace ProjectName.Migrations
{
    [DbContext(typeof(CarsContext))]
    partial class CarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ProjectName.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Honda"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Toyota"
                        },
                        new
                        {
                            ID = -4,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("ProjectName.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasDatabaseName("FK_Model_Manufacturer");

                    b.ToTable("model");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ManufacturerID = -1,
                            Name = "Eclipse"
                        },
                        new
                        {
                            ID = -2,
                            ManufacturerID = -1,
                            Name = "3000GT"
                        },
                        new
                        {
                            ID = -3,
                            ManufacturerID = -2,
                            Name = "NSX"
                        },
                        new
                        {
                            ID = -4,
                            ManufacturerID = -2,
                            Name = "S2000"
                        },
                        new
                        {
                            ID = -5,
                            ManufacturerID = -3,
                            Name = "Supra"
                        },
                        new
                        {
                            ID = -6,
                            ManufacturerID = -3,
                            Name = "MR2"
                        },
                        new
                        {
                            ID = -7,
                            ManufacturerID = -4,
                            Name = "300ZX"
                        },
                        new
                        {
                            ID = -8,
                            ManufacturerID = -4,
                            Name = "GTR"
                        });
                });

            modelBuilder.Entity("ProjectName.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("CHAR(17)")
                        .HasColumnName("vin");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("colour");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_year");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("purchase_date");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("sale_date");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("user_email");

                    b.HasKey("VIN");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("ProjectName.Models.Model", b =>
                {
                    b.HasOne("ProjectName.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("ProjectName.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
